### ISSUE TITLE
Plugin can no longer be published

### ISSUE THREAD

**Issue by britter** [arendd/AspectjGradlePlugin#4]
@britter I tried to publish the new version, but now the first of the new tests "can be applied via plugins block" failed.
Do you have any idea whats the reason ? When I skip this test the other tests are succesful, but the first one always fail:

`
[result.txt](https://github.com/arendd/AspectjGradlePlugin/files/5239586/result.txt)
`

_Originally posted by @arendd in https://github.com/arendd/AspectjGradlePlugin/pull/3#issuecomment-694255405_

**Comment by britter** [comment]
Looking at the provided log I suspect that the Gradle version being used to publish the plugin is too old. The changes I applied probably need something above Gradle 5.x. Since the wrapper in this repository is not correctly set up, I'd suggest that we set up the wrapper with a Gradle version that supports the changes that I made.

This raises the question what the minimum supported Gradle version should be. I'm fairly confident that after my changes the plugin works with Gradle 5.x. Some 6.x version don't seem to be supported due to #1. We'll need to look into that later.

**Comment by britter** [comment]
After some investigation I realized my changes from #3 don't work on Gradle 5.x. Since this plugin is supposed to work on Gradle 5/6 I need to find some other way to lazily evaluate the `aspectjVersion`. I need to think some more about this.

**Comment by arendd** [comment]
@britter Sorry for the delay, I merged your PR and successfully published version 0.0.5. Thank you again
